name: Publish
on:
  push:
    tags:
      - '**'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      CF_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
    steps:
      - name: Clone
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Publish
        uses: BigWigsMods/packager@v2